# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
remote_theme: "https://github.com/waridh/minimal-mistakes"
minimal_mistakes_skin: "contrast"

locale              : "en-US"

# Site settings
title: "Bach Wongwandanee"
title_separator: "|>"
name: &name "Bach Wongwandanee"

description         : "Personal website of Waridh (Bach) Wongwandanee."

baseurl: ""
url: "https://waridh.github.io"

repository          : "waridh/waridh.github.io"

teaser              : "/assets/images/meta/hello_summer_neon.jpg"

masthead_title      : "Waridh"

words_per_minute    : 200


# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/meta/portrait.jpg"
  bio              : "Computer Engineering student trying to be good at both hardware and software."
  location         : "Burnaby, BC"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "waridh@ualberta.ca"
    - label: "My other site"
      icon: "fas fa-fw fa-link"
      url: "https://waridh.ca"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://www.threads.net/@bach_w_w"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/waridh"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bach_w_w"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/waridh"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bach_w_w"

defaults:
  # _posts

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

atom_feed:
  hide: true

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6


